import { GalleryItem } from "@/types/gallery";

export const FALLBACK_GALLERY_ITEMS: GalleryItem[] = [
  {
    _id: "gal-1",
    title: "Crimson Solitude",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: 3 / 4,
    width: 1200,
    height: 1600,
    alt: "Solitary figure on dark volcanic rocks in red misty atmosphere",
    caption: "A lone explorer amid volcanic crags and heavy crimson fog.",
    tags: ["Atmosphere", "Crimson", "Minimalist"],
  },
  {
    _id: "gal-2",
    title: "Submerged Nocturne",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Dark ocean water with glowing red and deep blue reflections",
    caption: "Turbulent deep tides glowing with eerie crimson illumination.",
    tags: ["Ocean", "Night", "Cinematic"],
  },
  {
    _id: "gal-vid-1",
    title: "Dust of the Savannah",
    mediaType: "video",
    src: "/videos/ele.webm",
    poster: "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1920,
    height: 1080,
    alt: "Wild elephants marching through dusty golden savannah landscape",
    caption: "Majestic giant traversing the untamed African plains.",
    tags: ["Wildlife", "Savannah", "Video"],
  },
  {
    _id: "gal-3",
    title: "The Golden Blade",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Luminous metallic artifact illuminated by prism lens flare and light rays",
    caption: "An ancient relic bathed in iridescent amber and teal highlights.",
    tags: ["Light", "Cinematic", "Prism"],
  },
  {
    _id: "gal-4",
    title: "Nocturne Wayfarer",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Lone figure walking under an amber streetlight enveloped in dense night mist",
    caption: "A lone silhouette stands beneath glowing amber street lamps in fog.",
    tags: ["Nocturne", "Mist", "Urban"],
  },
  {
    _id: "gal-5",
    title: "Ascension of Light",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: 3 / 4,
    width: 1200,
    height: 1600,
    alt: "Hand reaching upward into divine shafts of diagonal volumetric light rays",
    caption: "Ethereal rays piercing through emerald darkness.",
    tags: ["Light", "Spiritual", "Shadow"],
  },
  {
    _id: "gal-vid-2",
    title: "Secrets of the Coral Abyss",
    mediaType: "video",
    src: "/videos/fish.webm",
    poster: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1920,
    height: 1080,
    alt: "Underwater coral reef with vibrant fish swimming through clear turquoise water",
    caption: "Silent wonders dwelling in the deep blue sanctuary.",
    tags: ["Marine", "Ocean", "Video"],
  },
  {
    _id: "gal-6",
    title: "The Red Monolith",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 4 / 3,
    width: 1600,
    height: 1200,
    alt: "Audience watching a glowing red luminous monolith in deep black space",
    caption: "Silhouettes gather before the crimson luminescence.",
    tags: ["Neon", "Dark", "Atmosphere"],
  },
  {
    _id: "gal-7",
    title: "Unpack The Secret",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Moody textured grainy clouds in deep warm twilight",
    caption: "Whispers in the mist and twilight shadows.",
    tags: ["Grain", "Texture", "Mood"],
  },
  {
    _id: "gal-8",
    title: "Shelter in the Pines",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1516431883659-655d41c09bf9?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: 4 / 5,
    width: 1200,
    height: 1500,
    alt: "Glowing glass bus stop shelter illuminating cold dark foggy pine forest",
    caption: "A warm amber beacon in the freezing midnight forest mist.",
    tags: ["Pines", "Amber", "Night"],
  },
  {
    _id: "gal-9",
    title: "Obsidian Ridge",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 9 / 16,
    width: 1080,
    height: 1920,
    alt: "Towering jagged mountain peaks cutting through dark storm clouds",
    caption: "Precipitous peaks standing tall against gathering squalls.",
    tags: ["Mountains", "Storm", "Vertical"],
  },
  {
    _id: "gal-10",
    title: "Bioluminescent Surge",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Crashing coastal waves glowing under starlight",
    caption: "The restless shoreline glowing in ethereal night hues.",
    tags: ["Coast", "Bioluminescence", "Night"],
  },
  {
    _id: "gal-11",
    title: "Emerald Sanctuary",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: 3 / 4,
    width: 1200,
    height: 1600,
    alt: "Sunlight filtering through dense ancient rainforest canopy",
    caption: "Ancient ferns and moss carpeted beneath cathedral trees.",
    tags: ["Forest", "Emerald", "Wild"],
  },
  {
    _id: "gal-12",
    title: "Ghost in the Embers",
    mediaType: "image",
    src: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1600&auto=format&fit=crop",
    aspectRatio: 16 / 9,
    width: 1600,
    height: 900,
    alt: "Campfire embers rising into the starry mountain atmosphere",
    caption: "Golden sparks dancing against the cold abyss of outer space.",
    tags: ["Campfire", "Stars", "Night"],
  },
];
